### ISSUE TITLE
Get rid of these files if you no longer need for the functionality of your app. Keep if they are for testing.

### ISSUE THREAD

**Issue by ryanaolea** [powerpuff-girls-fec/fec#28]
https://github.com/powerpuff-girls-fec/fec/blob/c4b65e61964b37f37052dd6c17720b8e0e5fad3f/client/src/components/productOverview/tempData/dummyProductInfo.js#L1

**Comment by BenjaminRCope** [comment]
They were originally included for early development, they have been removed from the relevant branch as of this morning or last night sometime
