### ISSUE TITLE
Consider keeping this path in your env.config folder and importing where needed. Will make refactoring for production much easier.

### ISSUE THREAD

**Issue by ryanaolea** [powerpuff-girls-fec/fec#30]
https://github.com/powerpuff-girls-fec/fec/blob/c4b65e61964b37f37052dd6c17720b8e0e5fad3f/client/src/components/questionsAndAnswers/ViewQuestionsAndAnswers.jsx#L18

**Comment by Zynh0722** [comment]
This should actually be using a relative path as it does here https://github.com/powerpuff-girls-fec/fec/blob/c4b65e61964b37f37052dd6c17720b8e0e5fad3f/client/src/components/reviews/Reviews.jsx#L25

if we had some secondary api that wasn't be served via the same server as that backend API middleman env would be the correct call

**Comment by Zynh0722** [comment]
@seanatrinh

**Comment by seanatrinh** [comment]
has been updated, closing!
