### ISSUE TITLE
Use more descriptive function names.

### ISSUE THREAD

**Issue by ryanaolea** [powerpuff-girls-fec/fec#32]
https://github.com/powerpuff-girls-fec/fec/blob/c4b65e61964b37f37052dd6c17720b8e0e5fad3f/client/src/components/reviews/review-list/Review.jsx#L35

**Comment by Zynh0722** [comment]
This is super descriptive!!!! the whole point of this is to mock web \<b> tags that can't be used in JSX @ryanaolea

**Comment by Zynh0722** [comment]
Hhahaha, had to escape that b tag, it proved my point a bit toooooo precisely

**Comment by Zynh0722** [comment]
Turns out \<b> just works now? https://github.com/powerpuff-girls-fec/fec/blob/a294d2bfde71b4f18504c3f8722b014f227fefa1/client/src/components/reviews/review-list/Review.jsx#L56
