### ISSUE TITLE
should use es6 arrow functions

### ISSUE THREAD

**Issue by Elliehunt8** [powerpuff-girls-fec/fec#34]
https://github.com/powerpuff-girls-fec/fec/blob/c4b65e61964b37f37052dd6c17720b8e0e5fad3f/client/src/components/App.jsx#L12

**Comment by Zynh0722** [comment]
I'm not sure how anything is gained from using arrow functions here, this solutions seems to be the most self descriptive and uses the least syntactic sugar, it's not a function expression, which as far as I'm aware are what you would normally replace with arrow functions.

**Comment by Elliehunt8** [comment]
const App = () => {
}
export default App 
is best practices and cleaner

**Comment by Zynh0722** [comment]
If that's best practices I'm going to argue with whoever decided that, breaking it into two lines is just worse in every way

**Comment by Zynh0722** [comment]
Also @Elliehunt8 this breaks AirBnB style guide which takes precedence https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/function-component-definition.md
