### ISSUE TITLE
Did I just get rick rolled? 

### ISSUE THREAD

**Issue by Elliehunt8** [powerpuff-girls-fec/fec#35]
https://github.com/powerpuff-girls-fec/fec/blob/c4b65e61964b37f37052dd6c17720b8e0e5fad3f/client/src/components/productOverview/productInformation/productInformation.jsx#L72

**Comment by BenjaminRCope** [comment]
I wanted to put something there as a placeholder while our widgets weren't linked together, thank you for reminding me to change it.
