### ISSUE TITLE
event should be passed through both parenthesis

### ISSUE THREAD

**Issue by Elliehunt8** [powerpuff-girls-fec/fec#36]
https://github.com/powerpuff-girls-fec/fec/blob/c4b65e61964b37f37052dd6c17720b8e0e5fad3f/client/src/components/productOverview/cart/quantity.jsx#L20

**Comment by BenjaminRCope** [comment]
Yeah, I can go through and do that. Is this a style thing? I don't see any effect on the code functionality.

**Comment by Elliehunt8** [comment]
The changeEvent value is implicitly passed in to onChange but if youre going to use the event in the function body its best practice to declare it in the variable declaration
