### ISSUE TITLE
Do these all need their own files? 

### ISSUE THREAD

**Issue by Elliehunt8** [powerpuff-girls-fec/fec#38]
https://github.com/powerpuff-girls-fec/fec/blob/c4b65e61964b37f37052dd6c17720b8e0e5fad3f/client/src/components/productOverview/productInformation/shareButtons/pinterestShare.jsx#L7

**Comment by BenjaminRCope** [comment]
These were separated out under the assumption they would take a lot more code to get working and to separate clutter out of the higher-level component. They've been reincorporated.
