### ISSUE TITLE
Is there a way to not need to keep repeating this in many of your files? 

### ISSUE THREAD

**Issue by Elliehunt8** [powerpuff-girls-fec/fec#39]
https://github.com/powerpuff-girls-fec/fec/blob/c4b65e61964b37f37052dd6c17720b8e0e5fad3f/client/src/components/productOverview/productInformation/prices.jsx#L27

**Comment by Zynh0722** [comment]
@Elliehunt8 Are you speaking of the use of proptypes? no, at least not with Airbnb style guide, anything that gets used *must* be in proptypes.

I think technically unused data could be omitted, but Im unsure in that regard

**Comment by Zynh0722** [comment]
Just went and tested proptypes, unused data can be omitted, logging this issue for cleaning pass

**Comment by Zynh0722** [comment]
Should clarify, proptypes will be in **any** component file that uses props, however the amount of data represented can likely be reduced.

**Comment by Zynh0722** [comment]
Closing in favor of #45
