### ISSUE TITLE
Consolidate some of these files 

### ISSUE THREAD

**Issue by Elliehunt8** [powerpuff-girls-fec/fec#40]
https://github.com/powerpuff-girls-fec/fec/blob/c4b65e61964b37f37052dd6c17720b8e0e5fad3f/client/src/components/questionsAndAnswers/QuestionsList/QuestionCard/AnswerCard/AnswerCard.jsx#L3

**Comment by seanatrinh** [comment]
Consolidated the answer card photo container, but maintained the separate button components since they have conditional rendering logic & API calls in them.
