### ISSUE TITLE
You don't need to 'import React, {useState}' you can just import {useState} from 'react'

### ISSUE THREAD

**Issue by Elliehunt8** [powerpuff-girls-fec/fec#43]
https://github.com/powerpuff-girls-fec/fec/blob/c4b65e61964b37f37052dd6c17720b8e0e5fad3f/client/src/components/reviews/Reviews.jsx#L1

**Comment by Zynh0722** [comment]
I think importing `React` is a habit from using class components previously, they _should_ be possible to remove, this was just on the backburner for when I do a cleaning pass of the repo

**Comment by Zynh0722** [comment]
Just clarified @Elliehunt8 This is incorrect, React must be in scope as jsx is used, so either it must be imported on a separate line, or left as it. As Airnbnb shows a warning for the latter case this will be left as is. Closing this issue
