### ISSUE TITLE
Can this be accomplished with less repetition

### ISSUE THREAD

**Issue by Elliehunt8** [powerpuff-girls-fec/fec#44]
https://github.com/powerpuff-girls-fec/fec/blob/c4b65e61964b37f37052dd6c17720b8e0e5fad3f/client/src/components/reviews/rating-breakdown/RatingBreakdown.jsx#L17

**Comment by Zynh0722** [comment]
I did this primarily because ratings is an object with keys 1-5, while I could loop those it felt uncouth. I'm exploring methods of converting it cleanly to an array now...

**Comment by Zynh0722** [comment]
https://github.com/powerpuff-girls-fec/fec/commit/240afdf2778e991f01cd1a4ca695a61f878d3f81

As I said, this solution feels less immediately clear, and less descriptive of the action that is being done, I think I preferred the old solution despite it being less dry @Elliehunt8
